crm/urls.py
    path("get/reasons/", views.ReasonListView.as_view(), name="get_reasons"),
    path("get/chassis/", views.GetChassisListView.as_view(), name="get_chassis"),
    path("get/state/", views.StateListView.as_view(), name="get_state"),
    # general
    path("opportunities/", views.OpportunityListView.as_view(), name="opportunity_list"),
    path("new/opportunity/", views.OpportunityCreateView.as_view(), name="opportunity_create"),
    path("opportunity/<str:pk>/", views.OpportunityDetailView.as_view(), name="opportunity_detail"),
    path("opportunity/<str:pk>/update/", views.OpportunityUpdateView.as_view(), name="opportunity_update"),
    path("opportunity/<str:pk>/delete/", views.OpportunityDeleteView.as_view(), name="opportunity_delete"),
    # opt followup
    path("opt/followup/<str:pk>/new/", views.OpportunityFollowUpCreateView.as_view(), name="followup_create"),
    path("opt/followup/<str:pk>/detail/", views.OpportunityFollowUpDetailView.as_view(), name="followup_detail"),
    path("opt/followup/<str:pk>/update/", views.OpportunityFollowUpUpdateView.as_view(), name="followup_update"),
    path("opt/testdrive/<str:pk>/", views.TestDriveRequestCreateView.as_view(), name="testdrive_create"),
    path("opt/testdrive/<str:pk>/update/", views.TestDriveRequestUpdateView.as_view(), name="testdrive_update"),
    path("opt/testdrive/<str:pk>/delete/", views.TestDriveRequestDeleteView.as_view(), name="testdrive_delete"),
    path("opt/lost-update/<str:pk>/", views.OpportunityLostCreateView.as_view(), name="opt_lost_create"),
    path("opt/lost-update/<str:pk>/update/", views.OpportunityLostUpdateView.as_view(), name="opt_lost_update"),
    path("opt/lost-update/<str:pk>/delete/", views.OpportunityLostDeleteView.as_view(), name="opt_lost_delete"),
    path("opt/booking-request/<str:pk>/", views.BookingRequestCreateView.as_view(), name="booking_request_create"),
    path(
        "opt/booking-request/<str:pk>/update/", views.BookingRequestUpdateView.as_view(), name="booking_request_update"
    ),
    path(
        "opt/booking-request/<str:pk>/delete/", views.BookingRequestDeleteView.as_view(), name="booking_request_delete"
    ),
    path("booking-tracker/", views.BookingTrackerListView.as_view(), name="booking_tracker_list"),
    path("booking-followup/<str:pk>/new/", views.BookingFollowUpCreateView.as_view(), name="booking_followup_create"),
    path(
        "booking-followup/<str:pk>/detail/", views.BookingFollowUpDetailView.as_view(), name="booking_followup_detail"
    ),
    path(
        "booking-followup/<str:pk>/update/", views.BookingFollowUpUpdateView.as_view(), name="booking_followup_update"
    ),
    path("booking/lost-update/<str:pk>/", views.BookingLostCreateView.as_view(), name="booking_lost_create"),
    path("booking/lost-update/<str:pk>/update/", views.BookingLostUpdateView.as_view(), name="booking_lost_update"),
    path("booking/lost-update/<str:pk>/delete/", views.BookingLostDeleteView.as_view(), name="booking_lost_delete"),
    # booking_cancelation_verfy_asm_gm_accounts
    path("booking-lost-list/", views.BookingLostListView.as_view(), name="booking_lost_list"),
    path(
        "booking-lost/dpt-update/<str:pk>/update/",
        views.BookingLostDptUpdateView.as_view(),
        name="booking_lost_dpt_update",
    ),
    path("back-order/<str:pk>/new/", views.BackOrderCreateView.as_view(), name="back_order_create"),
    path("chassis-block/<str:pk>/new/", views.ChassisBlockCreateView.as_view(), name="chassis_block_create"),
    path("invoice-request/<str:pk>/new/", views.BookingInvoiceCreateView.as_view(), name="invoice_request_create"),
    path("invoice-update/<str:pk>/update/", views.BookingInvoiceUpdateView.as_view(), name="invoice_request_update"),
    path("invoice-plan/<str:pk>/detail/", views.InvoicePlanDetailView.as_view(), name="invoice_plan_detail"),
    path("pending-testdrive/", views.PendingTestDriveListView.as_view(), name="pending_testdrive_list"),
    path("pending-testdrive/<str:pk>/update_status/", views.testdrive_status_update, name="testdrive_status_update"),
    path(
        "pending-testdrive/<str:pk>/update/",
        views.PendingTestDriveUpdateView.as_view(),
        name="pending_testdrive_update",
    ),
    path("invoice/discount/<str:pk>/", views.InvoicediscountDetailView.as_view(), name="invoice_discount_detail"),
    path("invoice/discount/<str:pk>/new/", views.InvoiceDiscountCreateView.as_view(), name="invoice_discount_create"),
    path(
        "invoice/discount/<str:pk>/update/", views.InvoiceDiscountUpdateView.as_view(), name="invoice_discount_update"
    ),
    path("invoice/accessory/<str:pk>/", views.InvoiceAccessoryDetailView.as_view(), name="invoice_accessory_detail"),
    path(
        "invoice/accessory/<str:pk>/new/", views.InvoiceAccessoryCreateVIew.as_view(), name="invoice_accessory_create"
    ),
    path(
        "invoice/accessory/<str:pk>/update/",
        views.InvoiceAccessoryUpdateView.as_view(),
        name="invoice_accessory_update",
    ),
    path("invoice/document/<str:pk>/new/", views.InvoiceDocumentUpdateView.as_view(), name="invoice_document_create"),
    # Deliveray list
    path("plan_pending/", views.PlanPendingListView.as_view(), name="plan_pending_list"),
    path("sale_support/", views.SaleSupportListView.as_view(), name="sale_support_list"),
    path("plan_accounts/", views.PlanAccountsListView.as_view(), name="plan_accounts"),
    # department verification
    path("invoice/finance/<str:pk>/update/", views.FinanceStatusUpdateView.as_view(), name="finance_status_update"),
    path("invoice/exchange/<str:pk>/update/", views.ExchangeStatusUpdateView.as_view(), name="exchange_status_update"),
    path(
        "invoice/registration/<str:pk>/update/",
        views.RegistrationStatusUpdateView.as_view(),
        name="registration_status_update",
    ),
    path("invoice/scheme/<str:pk>/update/", views.SchemeStatusUpdateView.as_view(), name="scheme_status_update"),
    path(
        "invoice/insurance/<str:pk>/update/", views.InsuranceStatusUpdateView.as_view(), name="insurance_status_update"
    ),
    path("invoice/pdi/<str:pk>/update/", views.PdiStatusUpdateView.as_view(), name="pdi_status_update"),
    path(
        "invoice/accessory_verification/<str:pk>/update/",
        views.AccessoryStatusUpdateView.as_view(),
        name="accessory_status_update",
    ),
    path(
        "invoice/discount_verification/<str:pk>/update/",
        views.DiscountStatusUpdateView.as_view(),
        name="discount_status_update",
    ),
    path(
        "each-pending-discount/<str:pk>/update_status/",
        views.each_discount_status_update,
        name="each_discount_status_update",
    ),
    path(
        "invoice/accounts_verification/<str:pk>/update/",
        views.AccountsStatusUpdateView.as_view(),
        name="accounts_status_update",
    ),
    # delivary
    path("delivary_pending/", views.DeliveryPendingListView.as_view(), name="delivary_pending_list"),
    path("delivered/", views.DeliveredListView.as_view(), name="delivered_list"),
    path("document_upload_accounts_team/", views.DocumentUploadAccountsTeamView.as_view(), name="document_upload_accounts_team"),
    path(
        "registration_remark/<str:pk>/", views.RegistrationRemarkCreateView.as_view(), name="registration_remark_create"
    ),
    path("invoice_accessory_list/", views.InvoiceAccessoryListView.as_view(), name="invoice_accessory_list"),
    path("accessory_job_card/<str:pk>/", views.JobcardView.as_view(), name="job_card"),
    path("gate_pass/<str:pk>/", views.GatepassView.as_view(), name="gate_pass"),
    path("update_to_deliverd/<str:pk>/", views.UpdatetoDeliverd.as_view(), name="update_to_delivered"),
    path(
        "delivered/followup/<str:pk>/new/",
        views.AfterDeliveryFollowupCreateView.as_view(),
        name="delivered_followup_create",
    ),
    path("after_delivery_followup_print/<str:pk>/", views.AfterDeliveryFollowupPrintView.as_view(), name="after_delivery_followup_print"),

    path("invoiced_requets/", views.InvoiceRejectedListView.as_view(), name="invoice_rejected_list"),
    path(
        "invoice_rejected_update/<str:pk>/update/",
        views.InvoiceRejectedUpdateView.as_view(),
        name="invoice_rejected_update",
    ),
    path(
        "each-pending-discount/<str:pk>/update_status/",
        views.each_discount_status_update,
        name="each_discount_status_update",
    ),
    # document
    path(
        "booking_invoice/document/<str:pk>/new/",
        views.BookingInvoiceDocumentCreateVIew.as_view(),
        name="booking_invoice_document_create",
    ),

    path("dailyreports/", views.DailyReportListView.as_view(), name="daily_report_list"),
    path("new/dailyreport/", views.DailyReportCreateView.as_view(), name="daily_report_create"),


    path("digital_leads/", views.DigitalLeadEnquiryListView.as_view(), name="digital_leads_list"),
    path("new/digital_lead/", views.DigitalLeadEnquiryCreateView.as_view(), name="digital_leads_create"),

    #digital lead followup /lost

    path("digital_lead/followup/<str:pk>/new/", views.DigitalLeadFollowUpCreateView.as_view(), name="digital_lead_followup_create"),
    path("digital_lead/lost-update/<str:pk>/", views.DigitalLeadLostCreateView.as_view(), name="digital_lead_lost_create"),


    path("eventreports/", views.EventReportListView.as_view(), name="event_report_list"),
    path("new/eventreport/", views.EventReportCreateView.as_view(), name="event_report_create"),
    path("event_report/<str:pk>/update/", views.EventReportUpdateView.as_view(), name="event_report_update"),

    path("event_photo/upload/<str:pk>/new/", views.EventPhotoUploadCreateView.as_view(), name="event_photo_create"),
    path("new/event/customer_details/<str:pk>/new/", views.EventCustomerDetailsCreateView.as_view(), name="event_customer_details_create"),
    # path("event/customer_details/list/", views.EventCustomerDetailsListView.as_view(), name="event_customer_details_list"),

    

indusmotors/urls.py
from core.mixins import OpenView

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.utils.translation import gettext_lazy as _


module_urls = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.simple.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("masters/", include("masters.urls", namespace="masters")),
    path("crm/", include("crm.urls", namespace="crm")),
    path("stock/", include("stock.urls", namespace="stock")),
    path("branches/", include("branches.urls", namespace="branches")),
    path("dms/", include("dms.urls", namespace="dms")),
    prefix_default_language=False,
)

plugin_urls = [
    path("tinymce/", include("tinymce.urls")),
    path("translate/", include("rosetta.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml", OpenView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", OpenView.as_view(template_name="robots.txt", content_type="text/plain")),
]

urlpatterns = (
    module_urls
    + plugin_urls
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

PROJECT_NAME = settings.APP_SETTINGS.get("site_name")
admin.site.site_header = _("%(project_name)s Administration") % {"project_name": PROJECT_NAME}
admin.site.site_title = _("%(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}
admin.site.index_title = _("Welcome to %(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}

stock/forms.py
from django import forms
from crm.models import BookingInvoice
from masters.models import CarModel, Color, District, State, Stock, Trim, Variant
from core.choices import  SELECTION_CHOICES, SELECTION_CHOICES_FINANCE


class BookingInvoiceUpdateFormStock(forms.ModelForm):
    car_model = forms.ModelChoiceField(queryset=CarModel.objects.all())
    trim = forms.ModelChoiceField(queryset=Trim.objects.all())
    color = forms.ModelChoiceField(queryset=Color.objects.all())
    variant = forms.ModelChoiceField(queryset=Variant.objects.all())
    chassis = forms.ModelChoiceField(queryset=Stock.objects.all())

    class Meta:
        model = BookingInvoice
        fields = ("car_model", "trim", "color", "variant", "chassis", "status", "remarks")


class BookingInvoiceUpdateFormInvoice(forms.ModelForm):
    class Meta:
        model = BookingInvoice
        fields = (
            "invoice_date",
            "invoice_no",
            "consumer_offer",
            "consumer_offer_campaign_code",
            "consumer_offer_amount",
            "consumer_dealer_share",
            "consumer_tml_share",
            "isl_scheme",
            "isl_offer_campaign_code",
            "isl_share",
            "isl_dealer_share",
            "total_isl_amount",
            "invoice_scheme_name",
            "invoice_scheme_campaign_code",
            "invoice_scheme_dealer_share",
            "invoice_scheme_tml_share",
            "invoice_scheme_total_amount",
            "invoice_yono_name",
            "invoice_yono_campaign_code",
            "invoice_yono_dealer_share",
            "invoice_yono_tml_share",
            "invoice_yono_total_amount",
            "invoice_exchange_name",
            "invoice_exchange_campaign_code",
            "invoice_exchange_dealer_share",
            "invoice_exchange_tml_share",
            "invoice_exchange_total_amount",



        )


class BookingInvoiceUpdateFormTeamLead(forms.ModelForm):
    is_temp_address = forms.ChoiceField(choices=SELECTION_CHOICES,widget=forms.Select(attrs={"class": "form-control w-20"}),)
    is_scheme = forms.ChoiceField(choices=SELECTION_CHOICES,widget=forms.Select(attrs={"class": "form-control w-20"}),)
    is_yono_scheme = forms.ChoiceField(choices=SELECTION_CHOICES,widget=forms.Select(attrs={"class": "form-control w-20"}),)
    is_finance = forms.ChoiceField(choices=SELECTION_CHOICES_FINANCE,widget=forms.Select(attrs={"class": "form-control w-40"}),)


    state = forms.ModelChoiceField(queryset=State.objects.all(), label="State")
    district = forms.ModelChoiceField(queryset=District.objects.all(), label="District")
    # temp address
    temp_state = forms.ModelChoiceField(queryset=State.objects.all(), label="State", required=False)
    temp_district = forms.ModelChoiceField(queryset=District.objects.all(), label="District", required=False)

    invoice_no = forms.CharField(widget=forms.TextInput(attrs={"readonly": "readonly"}))

    class Meta:
        model = BookingInvoice
        fields = (
            "invoice_no",
            "dse",
            "customer_salutation",
            "customer_name",
            "mobile",
            "email",
            "guardian_salutation",
            "guardian_name",
            "dob",
            "house_name",
            "place",
            "panchayath",
            "village",
            "post",
            "pin",
            "state",
            "district",
            "temp_house_name",
            "temp_place",
            "temp_panchayath",
            "temp_village",
            "temp_post",
            "temp_pin",
            "temp_state",
            "temp_district",
            # registration
            "reg_type",
            "rto",
            "reg_remarks",
            "any_tax_exemption",
            "tax_remarks",
            # insurance
            "insurance_type",
            "ncb_eligibility",
            "ncb_percentage",
            "any_other_discount",
            "insurance_remarks",
            "nominee_name",
            "dob_of_nominee",
            "nominee_relation",
            # scheme
            "scheme",
            "scheme_name",
            "institution_name",
            "amount",
            "yono_scheme_amount",
            # finance
            "finance",
            "branch",
            "loan_amount",
            "executive",

            "is_temp_address",
            "is_scheme",
            "is_yono_scheme",
            "is_finance",
        )

templates/app/partials/discount_status_form.html
{% if request.user.usertype == 'asm' or request.user.usertype == 'sm'%}
<form action="{% url 'crm:each_discount_status_update' record.pk %}" method="GET" class="each_discount_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">
        <option value="pending" {% if record.discount_status == 'pending' %} selected {% endif %} >Pending</option>
        <option value="escalate" {% if record.discount_status == 'escalate' %} selected {% endif %} >Escalate</option>
        <option value="approve" {% if record.discount_status == 'approve' %} selected {% endif %} >Approve</option>
        <option value="reject" {% if record.discount_status == 'reject' %} selected {% endif %} >Reject</option>
    </select>
</form>
{% elif request.user.usertype == 'gm'  %}
    <form action="{% url 'crm:each_discount_status_update' record.pk %}" method="GET" class="each_discount_update_form">
        <select name="status" id="status" class="form-control niceselect" style="width:auto">
           
            {% if record.discount_status == 'escalate' %}
            <option value="escalate" {% if record.discount_status == 'escalate' %} selected {% endif %} >Escalate</option>
            <option value="approve" {% if record.discount_status == 'approve' %} selected {% endif %} >Approve</option>
            <option value="reject" {% if record.discount_status == 'reject' %} selected {% endif %} >Reject</option>
            {% endif %}

            {% if record.discount_status == 'approve' %}
            <option value="approve" {% if record.discount_status == 'approve' %} selected {% endif %} >Approve</option>
            <option value="reject" {% if record.discount_status == 'reject' %} selected {% endif %} >Reject</option>
            {% endif %}

        </select>
    </form>
{% else %}
    {{ record.get_discount_status_display }}
{% endif %}















{% comment %} 

{% if request.user.usertype == 'asm' or request.user.usertype == 'sm' or request.user.usertype == 'gm' %}
<form action="{% url 'crm:each_discount_status_update' record.pk %}" method="GET" class="each_discount_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">

        <option value="pending" {% if record.discount_status == 'pending' %} selected {% endif %} >Pending</option>
        <option value="escalate" {% if record.discount_status == 'escalate' %} selected {% endif %} >Escalate</option>
        
        <option value="approve" {% if record.discount_status == 'approve' %} selected {% endif %} >Approve</option>
        <option value="reject" {% if record.discount_status == 'reject' %} selected {% endif %} >Reject</option>

        

    </select>
</form>
{% else %}
    {{ record.get_discount_status_display }}
{% endif %} {% endcomment %}

templates/app/partials/district_selector.html
<script>
    var get_state_url = "{% url 'crm:get_state' %}";
    var stateSelect = $("#id_state");


    function updateSelectOptions(selectId, data, valueKey, textKey) {
        const select = $(selectId);
        select.empty().append('<option value="" selected="selected">---------</option>');
        if (data) {
            const options = data.map(item => `<option value="${item[valueKey]}">${item[textKey]}</option>`);
            select.append(options.join(''));
        }
    }

    function makeAjaxCall(get_state_url,data,successCallback) {
        
        $.ajax({
            url: get_state_url,
            data: data,
            dataType: 'json',
            success: successCallback
        });
    }

    stateSelect.change(function () {
        let state = stateSelect.val();
        let data = { state: state };
        console.log(get_state_url)

        makeAjaxCall(data, function (data) {
            updateSelectOptions("#id_district", data.district, "id", "name");
        });
    });


</script>

templates/app/partials/loader.html
{% load static %}
<!---Global-loader-->
<div id="global-loader">
	<img src="{% static 'app/images/svgs/loader.svg' %}" alt="loader">
</div>

templates/app/partials/opt_variant_selector.html
<script>
    var get_url = "{% url 'crm:get_variants' %}";
    var carModelSelect = $("#id_car_model");
    var trimSelect = $("#id_trim");
    var colorSelect = $("#id_color");

    function updateSelectOptions(selectId, data, valueKey, textKey) {
        const select = $(selectId);
        select.empty().append('<option value="" selected="selected">---------</option>');
        if (data) {
            const options = data.map(item => `<option value="${item[valueKey]}">${item[textKey]}</option>`);
            select.append(options.join(''));
        }
    }

    function makeAjaxCallCar(get_url, data, successCallback) {
        $.ajax({
            url: get_url,
            data: data,
            dataType: 'json',
            success: successCallback
        });
    }

    carModelSelect.change(function () {
        let carModel = carModelSelect.val();
        let data = { car_model: carModel };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions("#id_trim", data.trims, "trim__id", "trim__name");
            updateSelectOptions("#id_color", data.colors, "color__id", "color__name");
            updateSelectOptions("#id_variant", data.variants, "id", "vehicle_code");
            updateSelectOptions("#id_chassis", data.variants, "id", "chassis_number");
        });
    });

    trimSelect.change(function () {
        let carModel = carModelSelect.val();
        let trim = trimSelect.val();
        let data = { car_model: carModel, trim: trim };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions("#id_color", data.colors, "color__id", "color__name");
            updateSelectOptions("#id_variant", data.variants, "id", "vehicle_code");
        });
    });

    colorSelect.change(function () {
        let carModel = carModelSelect.val();
        let trim = trimSelect.val();
        let color = colorSelect.val();
        let data = { car_model: carModel, trim: trim, color: color };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions2("#id_variant", data.variants, "id", "vehicle_code");
            function updateSelectOptions2(selectId, data, valueKey, textKey) {
                const select = $("#id_variant");
                select.empty().append('<option value="" >---------</option>');
                if (data) {
                    const options = data.map(item => `<option value="${item[valueKey]}" selected="selected">${item[textKey]}</option>`);
                    select.append(options.join(''));
                }
            }
        });
    });

</script>

templates/app/partials/table_actions_delivary_pending.html
<ul>
    {% if request.user.usertype == 'registration_bo' %}
        <li><a class="btn btn-sm btn-primary mb-1" href="{{record.registration_remark_create_url}}">Add Remarks</a></li>
        <li>
            <button type="button"  class=" form20-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload Form20"  data-form-type='form20_upload'>
                Upload Form20
            </button>
        </li>
        <li>
            <button type="button"  class=" disclimer-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload Disclimer" data-form-type='disclimer_upload'>
                Upload Disclimer
            </button>
        </li>
        <li>
            <button type="button" class=" undertaking-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload Undertaking" data-form-type='undertaking_upload'>
                Upload Undertaking
            </button>
        </li>
    {% elif request.user.usertype == 'accounts' %}
        <li>
            <button type="button"  class=" invoice-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}"   data-document-name="Upload Invoice" data-form-type='invoice_upload'>
                Upload Invoice
            </button>
        </li>
        <li>
            <button type="button" class=" settlement-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload Settlement" data-form-type='settlement_upload'>
                Upload Settlement
            </button>
        </li>
        <li>
            <button type="button"  class="receipt-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload Receipts" data-form-type='receipts_upload'>
                Upload Receipts
            </button>
        </li>

        {% elif request.user.usertype == 'tmga' %}
        <li>
            <button type="button"  class=" accessory-bill-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}"   data-document-name="Upload Accessory Bill" data-form-type='accessory_bill_upload'>
                Upload Accessory Bill
            </button>
        </li>
        
    {% else %}
        <li><a class="btn btn-sm btn-primary mb-1" href="{% url 'crm:gate_pass' record.pk %}" target="_blank">Gate Pass</a></li>
        <li><a class="btn btn-sm btn-primary mb-1" href="{% url 'crm:update_to_delivered' record.pk %}">Update</a></li>
        <li>
            <button type="button" class="signed_form20-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload  signed Form20" data-form-type='signed_form20_upload'>
                Upload signed Form20
            </button>
        </li>
        <li>
            <button type="button"  class=" signed_disclimer-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}" data-document-name="Upload signed Disclimer" data-form-type='signed_disclimer_upload'>
                Upload signed Disclimer
            </button>
        </li>
        <li>
            <button type="button"  class=" signed_undertaking-add-btn btn btn-primary mb-1 document-upload" data-bs-toggle="modal" data-bs-target="#consolidated-modal" data-invoice-id="{{record.pk}}"  data-document-name="Upload signed Undertaking" data-form-type='signed_undertaking_upload'>
                Upload signed Undertaking
            </button>
        </li>
        
    {% endif %}
</ul>

templates/app/partials/variant_selector.html
<script>
    var get_url = "{% url 'crm:get_variants' %}";
    var carModelSelect = $("#id_car_model");
    var trimSelect = $("#id_trim");
    var colorSelect = $("#id_color");

    function updateSelectOptions(selectId, data, valueKey, textKey) {
        const select = $(selectId);
        select.empty().append('<option value="" selected="selected">---------</option>');
        if (data) {
            const options = data.map(item => `<option value="${item[valueKey]}">${item[textKey]}</option>`);
            select.append(options.join(''));
        }
    }

    function makeAjaxCallCar(get_url, data, successCallback) {
        $.ajax({
            url: get_url,
            data: data,
            dataType: 'json',
            success: successCallback
        });
    }

    carModelSelect.change(function () {
        let carModel = carModelSelect.val();
        let data = { car_model: carModel };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions("#id_trim", data.trims, "trim__id", "trim__name");
            updateSelectOptions("#id_color", data.colors, "color__id", "color__name");
            updateSelectOptions("#id_variant", data.variants, "id", "vehicle_code");
            updateSelectOptions("#id_chassis", data.variants, "id", "chassis_number");
        });
    });

    trimSelect.change(function () {
        let carModel = carModelSelect.val();
        let trim = trimSelect.val();
        let data = { car_model: carModel, trim: trim };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions("#id_color", data.colors, "color__id", "color__name");
            updateSelectOptions("#id_variant", data.variants, "id", "vehicle_code");
        });
    });

    colorSelect.change(function () {
        let carModel = carModelSelect.val();
        let trim = trimSelect.val();
        let color = colorSelect.val();
        let data = { car_model: carModel, trim: trim, color: color };

        makeAjaxCallCar(get_url, data, function (data) {
            updateSelectOptions("#id_variant", data.variants, "id", "vehicle_code");
            
        });
    });

</script>